server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React Router — tüm path'leri index.html'e yönlendir
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Sıkıştırma
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript;
}
